version: 1.0.{build}
image: Visual Studio 2017
build_script:
- cmd: >-
    dotnet build -c release src/NJsonSchema/NJsonSchema.csproj

    dotnet pack -c release src/NJsonSchema/NJsonSchema.csproj /p:Version=%APPVEYOR_BUILD_VERSION% 

    dotnet nuget push src/NJsonSchema/bin/release/NJsonSchema.%APPVEYOR_BUILD_VERSION%.nupkg -k %NUGET_API_KEY% -s %NUGET_URL%
